[package]
name = "macro-rs"
version = "0.2.0"
edition = "2024"

[features]
save = ["serde_json"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }

device_query = "3"
enigo = "0.5"

[dev-dependencies]
serde_json = "1"